# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- azurepipeline_cicd


pool: Denodo_cicd_agent_pool
name: 'Denodo_cicd_agent'

steps:

- script: echo Hello, world!
- script: echo %PASSWORD%