trigger:
  branches:
    include:
    - main

- name: pool
  value: Denodo_cicd_agent_pool
- name: name
  value: 'Denodo_cicd_agent'
stages:
- stage: __default
  jobs:
  - job: AgentJob1
    pool:
      name: 'Denodo_cicd_agent_pool'
      steps:

      - task: ManualValidation@0
        inputs:
         notifyUsers:'pintu.sadhu@ltimindtree.com'
         
  - job: AgentJob2
    pool:
      name: 'Denodo_cicd_agent_pool'
    steps:
    - task: CmdLine@2
      displayName: 'Echo Output'
      inputs:
        script: |
          REM Echo Output command
          echo 'Hello WORLD'
    

