# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- azurepipeline_cicd

variables:

- name: denodoPath  # name of a variable
  value: 'C:\Denodo\DenodoPlatform8.0\bin' # value of the variable
- name: server  # name of a variable
  value: 'dnd-v-yisc003a.centralindia.cloudapp.azure.com:9999/project2' # value of the variable
- name: vqlFileName  # name of a variable
  value: 'vcscommand.vql' # value of the variable
- name: testingToolConfig  # name of a variable
  value: 'configuration.properties' # value of the variable
- name: testingToolTest  # name of a variable
  value: 'test1.denodotest' # value of the variable
- name: pipelineTmpPath  # name of a variable
  value: 'C:\Denodo\DenodoPlatform8.0\pipeline_files' # value of the variable



pool: Denodo_cicd_agent_pool
name: 'Denodo_cicd_agent'

steps:
    - script: |
REM Create VQL file with DVCSPULL command
echo DVCSPULL project1; > %pipelineTmpPath%\%vqlFileName%
