# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:

 - name: denodoPath
   value: 'C:/Denodo/DenodoPlatform8.0/bin'

 - name: testingToolPath
   value: 'C:/Denodo/denodo-testing-tool-8.0-20230425'




- name: pipelineTmpPath
value: 'C:/Denodo/DenodoPlatform8.0/pipeline_files'

- name: server
value: 'localhost:9999/project1'

- name: vqlFileName
value: 'vcscommand.vql'

- name: testingToolConfig
value: 'configuration.properties'

- name: testingToolTest
value: 'test1.denodotest'

jobs:
- job: AgentJob
pool: Denodo_cicd_agent_pool
name: 'Denodo_cicd_agent'

steps:
