# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool: Denodo_cicd_agent_pool
name: 'Denodo_cicd_agent'

steps:
    - task: ManualValidation@0
    inputs:
         notifyUsers:'pintu.sadhu@ltimindtree.com'

 steps:
    - task: CmdLine@2
      script: echo Hello, world!

