# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azurepipeline_cicd # This indicates that the pipeline will fire automatically when there are changes to the main branch.

variables:

- name: denodoPath  # name of a variable
  value: 'C:\Denodo\DenodoPlatform8.0\bin' # value of the variable

jobs:
- job: AgentJob
pool: Denodo_cicd_agent_pool
name: 'Denodo_cicd_agent'
steps:
- script: |
REM Create VQL file with DVCSPULL command
echo $(denodoPath)