trigger:
  branches:
    include:
    - main
variables:
- name: pool
  value: Denodo_cicd_agent_pool
- name: name
  value: 'Denodo_cicd_agent'
stages:
- stage: __default
  jobs:
  - job: AgentJob1
    pool:
      name: 'Denodo_cicd_agent_pool'
      steps:

      - task: ManualValidation@0
        inputs:
         notifyUsers:'pintu.sadhu@ltimindtree.com'
         

    steps:
    - task: CmdLine@2
      displayName: 'Command Output'
      inputs:
        script: |
          REM Print command
          echo Hello World
    

